name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Application
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      # ==========================================
      #      Load kubeconfig (ONLY ONE CORRECT)
      # ==========================================
      - name: File create k8s
        run: echo "$KUBECONFIG_CONTENT" > kubeconfig-embedded.yaml

      - name: Test K8s connection
        run: kubectl --kubeconfig=kubeconfig-embedded.yaml get nodes

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Test K8s Connection
        run: kubectl get nodes

      # ==========================================
      #             Deploy to K8s
      # ==========================================
      - name: Update K8s Deployment Image
        run: |
          kubectl set image deployment/myapp1-deployment \
            myappdemo=${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest -n default

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/myapp1-deployment -n default
